name: Build and test TChecker
on:
  push:
    branches:
      - '**'

jobs:
  build-and-test-linux:
    name: build-and-test-linux
    strategy: 
      matrix: 
        intsize: ["all:int16:memcheck", "all:int32:memcheck", "all:int64:memcheck"]
        compiler: ["gcc", "clang"]
    runs-on: ubuntu-latest
    container: alzeha/echtzeitsysteme-tchecker-${{ matrix.compiler }}:v0.1
    env:
      CONFNAME: ${{ matrix.intsize }}
      INSTALL_DIR: "install"
      TCHECKER_BUILD_TYPE: "Debug"
      
    steps:
      - uses: actions/checkout@v4
      - name: build-and-test
        run: ci-scripts/github-ubuntu-build-and-test-${{ matrix.compiler }}.sh
