name: Build and test TChecker
on:
  push:
    branches:
      - '*'

env:
  CATCH2_REPO_URL : https://github.com/catchorg/Catch2.git
  CATCH2_BRANCH : v3.4.0
  TCHECKER_BUILD_TYPE : Debug
  BUILD_TYPE : Debug
  NB_CPUS : 2
  CATCH2_DIRECTORY : ${{ github.workspace }}/tmp/Catch2
  INSTALL_DIR : ${{ github.workspace }}/tmp/install

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        intsize: [int16, int32, int64]
        compiler: [gcc, clang]
    name: ${{ matrix.os }} / ${{ matrix.intsize }} / ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    env:
      CONFNAME: all:${{ matrix.intsize }}:memcheck
    steps:
      - name: Set compiler variables
        run: |        
          {
            if test "${{matrix.compiler}}" = "gcc"; then
              echo "CC=gcc"
              echo "CXX=g++"
              echo "CONFNAME=all:${{ matrix.intsize }}:memcheck"
            else 
              echo "CC=clang"
              echo "CXX=clang++"
              echo "CONFNAME=all:${{ matrix.intsize }}"
            fi
          } >> "$GITHUB_ENV"
      - name: Getting project repo
        uses: actions/checkout@v3

      - if: ${{ matrix.os == 'macos-latest' }}
        run: echo "/usr/local/opt/bison/bin" >> $GITHUB_PATH

      - name: Install pre-requesites
        run: |
          sudo ci-scripts/install-$RUNNER_OS.sh
          ci-scripts/show-config.sh
      - name: Build TChecker
        run: ci-scripts/build.sh
      - name: Testing TChecker
        run: ci-scripts/test.sh
